# Generated by Django 4.1.6 on 2023-02-23 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0002_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='tada',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tada.tada'),
            preserve_default=False,
        ),
    ]
