# Generated by Django 4.1.6 on 2023-02-23 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0004_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_name', models.CharField(max_length=200)),
                ('setting_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tada.module')),
                ('tada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tada.tada')),
            ],
        ),
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
