# Generated by Django 4.1.6 on 2023-02-23 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0005_setting_delete_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tada.module'),
        ),
    ]
